name: Testes

on: [push, pull_request]

jobs:
  testes:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verificar código
      run: |
        python -m pip install --upgrade pip
        python -m unittest ../../testes.py
